# Cover fundamental concepts of tensors using Tensorflow

* Introduction to Tensors
* Getting information from Tensors
* Manipulating Tensors
* Tensors $ Numpy
* Using @tf.function (to speed up regular python functions)
* Using GPU's with Tensorflow
* Exercise

## Introduction to Tensors

In [ ]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.12.0


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check no of dimensions of a tensor
scalar.ndim

0

In [ ]:
# create a vector
vector = tf.constant([10,50])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 50], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
# Create a matrix
matrix = tf.constant([[10,20,2],
                     [30,40,4]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 20,  2],
       [30, 40,  4]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#Create another matrix
another_matrix = tf.constant([[10.,7.],
                             [3.,2.],
                             [2.,4.]])
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 2.,  4.]], dtype=float32)>

In [ ]:
#Create a tensor
tensor = tf.constant([[[1,2,3]],
                     [[4,5,6]],
                     [[7,8,9]],
                     [[11,12,13]]])
tensor

<tf.Tensor: shape=(4, 1, 3), dtype=int32, numpy=
array([[[ 1,  2,  3]],

       [[ 4,  5,  6]],

       [[ 7,  8,  9]],

       [[11, 12, 13]]], dtype=int32)>

In [ ]:
tensor.ndim

3

* Scalar: a single number
* Vector: a numer with direction
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers
n = 0 : scalar
n = 1 : vector